# http://travis-ci.org/#!/ipython/ipython_widgets
language: python
python:
    - 3.4
    - 2.7
sudo: false
env:
  matrix:
    - GROUP=python
    - GROUP=js
before_install:
    - 'if [[ $GROUP == js* ]]; then npm install -g casperjs; fi'
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install -f travis-wheels/wheelhouse -r requirements.txt
    - npm install && gulp css
    - pip install -f travis-wheels/wheelhouse file://$PWD#egg=ipython_widgets[test] coveralls
script:
    - 'if [[ $GROUP == js ]]; then python -m ipython_widgets.jstest; fi'
    - 'if [[ $GROUP == python ]]; then nosetests --with-coverage --cover-package=ipython_widgets ipython_widgets; fi'
matrix:
    include:
        - python: 3.3
          env: GROUP=python

after_success:
    - coveralls
